theme = "hugo-now-ui"
languageCode = "en-us"
title = "DS4E"
googleAnalytics = "UA-179064457-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#enableGitInfo = true
publishDir = "docs/"

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    identifier = "github"
    url = "https://github.com/berkeley-ds4e"
    pre = "<i class='fa fa-github'></i>"
    weight = 2    
[[menu.main]]
    name = ""
    identifier = "email"
    url = "mailto:"
    pre = "<i class='now-ui-icons now-ui-icons ui-1_email-85'></i>"
    weight = 3

[[menu.footer]]
    name = ""
    identifier = "email"
    url = "mailto:"
    pre = "<i class='now-ui-icons now-ui-icons ui-1_email-85'></i>"
    weight = 3


[params]
    background = "img/parrot.jpg"
    tint = "blue"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"




