theme = "hugo-now-ui"
languageCode = "en-us"
title = "DS4E"
googleAnalytics = "UA-179064457-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#enableGitInfo = true
publishDir = "docs/"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    identifier = "twitter"
    url = "https://twitter.com/berkeley-ds4e"
    pre = "<i class='fa fa-twitter'></i>"
    weight = 1
[[menu.main]]
    identifier = "github"
    url = "https://github.com/berkeley-ds4e"
    pre = "<i class='fa fa-github'></i>"
    weight = 2    
[[menu.main]]
    name = ""
    identifier = "email"
    url = "mailto:berkeley.edu"
    pre = "<i class='now-ui-icons ui-1_send'></i>"
    weight = 3

[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/berkeley-ds4e"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "img/parrot.jpg"
    tint = "blue"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"




